### ISSUE TITLE
DefaultSetting.hashCode() should use Objects.hash()

### ISSUE THREAD

**Issue by dagnir** [HawaiiStateDigitalArchives/PID-webservice#3]
The `hashCode()` method can be simplified using [`Objects.hash(Object...)`](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#hash-java.lang.Object...-)

**Comment by Khyzad** [comment]
Don't they already do? These hash code methods were auto generated by Netbeans and they already use them. They multiple these values by random prime numbers to reduce collisions. Or would you prefer that they simple return Objects.hash(...)

**Comment by dagnir** [comment]
[`Objects.hash(Object...)`](https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#hash%28java.lang.Object...%29) is meant to simplify implementation `hashCode()`. It goes a step further than just using `Objects.hashCode(Object)` in that it will mix the hashes for you as well, which the method is still doing manually.  It delegates to `Arrays.hashCode()` which looks like this:

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7-b147/java/util/Arrays.java#Arrays.hashCode%28java.lang.Object%5B%5D%29

**Comment by dagnir** [comment]
For example instead of

``` java
int hash = 7;
hash = 43 * hash + Objects.hashCode(foo);
hash = 43 * hash + Objects.hashCode(bar);
```

it can be

``` java
int has = Objects.hashCode(foo,bar);
```
